name: aadhaar_hackathon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.0
  - numpy>=1.24
  - plotly>=5.17
  - streamlit>=1.28
  - scikit-learn>=1.3
  - prophet>=1.1
  - jupyter
  - ipykernel
